//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoshkola
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int Id { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Change1 { get; set; }
        public string Change2 { get; set; }
        public string Change3 { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
